### ISSUE TITLE
[FEATURE] WebRTC Metrics

### ISSUE THREAD

**Issue by disa6302** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-c#578]
**Is your feature request related to a problem? Please describe.**
An application using the WebRTC SDK expects to monitor the performance of the underlying SDK performance and to provide the flexibility for the applications to take decisions based on a metric

**Describe the solution you'd like**
The application should be able to pull the metrics out periodically based on a type. The following is a broad list of metrics that would be tracked:

- [x] ICE Candidate - #638 (@disa6302 )
- [x] ICE Candidate Pair (@disa6302 )
- [x] ICE Server - #598 (@disa6302 )
- [x] Remote Inbound RTP Stats - #615 (@zhuker )
- [x] Outbound RTP Stats - #615 (@zhuker )
- [x] Inbound stats - #673  (@zhuker )
- [x] Signaling - #577 (@MushMal )
- [x]  Data channel - #704 (@disa6302 )

Related to #576

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/577 for Signaling metrics

**Comment by zhuker** [comment]
@disa6302
>    I will merge this into awslabs:set-up-ice-metrics, but, I am splitting the different ICE metrics work into different branches to avoid a huge PR with lot of changes. Just FYI.

do you mind sharing them as separate PRs?

 how do we avoid duplicate work?

**Comment by zhuker** [comment]
working on
- Inbound RTP Stats
- Outbound RTP Stats

specifically focused on round trip times

**Comment by disa6302** [comment]
@zhuker ,

Thank you for your contribution once again. I am so thrilled to see your active participation! I should have added more details around the work distribution. RTP stats sounds good. I will add more details to the ticket.

**Comment by disa6302** [comment]
@zhuker , 

Outbound stats are merged :)
Great work!

**Comment by zhuker** [comment]
Thanks

**Comment by zhuker** [comment]
@disa6302 inbound stats https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/673

**Comment by zhuker** [comment]
@disa6302 i will need data channel stats as well
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/pull/697

**Comment by disa6302** [comment]
@zhuker , 

Sure! I can work on it. Should not take long to implement.

**Comment by zhuker** [comment]
> [ ] Data channel (@disa6302 )

were you already working on it?

**Comment by disa6302** [comment]
> > [ ] Data channel (@disa6302 )
> 
> were you already working on it?

I am half way through.

**Comment by disa6302** [comment]
@zhuker ,

Data channel stats are merged. Do let me know if something does not work for you.

**Comment by disa6302** [comment]
Completed the list of metrics. Closing.
